#!/bin/bash
###
# File: clone
# Author: Leopold Meinel (leo@meinel.dev)
# -----
# Copyright (c) 2022 Leopold Meinel & contributors
# SPDX ID: GPL-3.0-or-later
# URL: https://www.gnu.org/licenses/gpl-3.0-standalone.html
# -----
###

NAME="LeoMeinel"

PAGE=1
case "$1" in
all)
    while curl -s "https://api.github.com/users/$2/repos?page=$PAGE&per_page=100" | grep -q "ssh_url"; do
        SSH_URLS=$(curl -s "https://api.github.com/users/$2/repos?page=$PAGE&per_page=100" | grep -e 'ssh_url' | cut -d \" -f 4)
        xargs -L 1 git -C "$3" clone <<<"$SSH_URLS"
        PAGE=$((PAGE + 1))
    done
    ;;
esac
