#!/bin/bash
###
# File: gradle
# Author: Leopold Meinel (leo@meinel.dev)
# -----
# Copyright (c) 2022 Leopold Meinel & contributors
# SPDX ID: GPL-3.0-or-later
# URL: https://www.gnu.org/licenses/gpl-3.0-standalone.html
# -----
###

DIRECTORIES=$(/usr/bin/find "$2" -type f -name 'build.gradle' -printf '%h\n' | sort -u)
case "$1" in
update)
    for directory in $DIRECTORIES; do
        cd "$directory"
        gradle wrapper --gradle-version 7.5.1
    done
    ;;
build)
    for directory in $DIRECTORIES; do
        cd "$directory"
        gradle build
    done
    ;;
move)
    for directory in $DIRECTORIES; do
        cp "$directory"/build/libs/* "$3"
        rm -rf "$directory"/build/libs/*
    done
    ;;
clean)
    for directory in $DIRECTORIES; do
        cd "$directory"
        gradle clean
        rm -rf "$directory"/build
        rm -rf "$directory"/bin
        rm -rf "$directory"/.gradle
    done
    ;;
esac
cd ~
