#!/bin/bash
###
# File: gradle
# Author: Leopold Meinel (leo@meinel.dev)
# -----
# Copyright (c) 2023 Leopold Meinel & contributors
# SPDX ID: GPL-3.0-or-later
# URL: https://www.gnu.org/licenses/gpl-3.0-standalone.html
# -----
###

SOURCE_DIR="$2"
: ${SOURCE_DIR:=~/src}
DEBUG_DIR="$3"
: ${DEBUG_DIR:=~/src/20-debug}

set -eu

DIRECTORIES=$(/usr/bin/find "$SOURCE_DIR" -type f -name 'build.gradle' -printf '%h\n' | sort -u)
case "$1" in
update)
    for directory in $DIRECTORIES; do
        cd "${directory:?}"
        gradle wrapper --gradle-version 8.1.1
    done
    ;;
build)
    mkdir -p "${DEBUG_DIR:?}/"java/papermc/plugins
    for directory in $DIRECTORIES; do
        cd "${directory:?}"
        # Build
        gradle build
        # Move
        cp "${directory:?}/"build/libs/* "${DEBUG_DIR:?}/"java/papermc/plugins
        # Clean
        gradle clean
        rm -rf "${directory:?}/"build
        rm -rf "${directory:?}/"bin
        rm -rf "${directory:?}/".gradle
    done
    ;;
clean)
    for directory in $DIRECTORIES; do
        cd "${directory:?}"
        gradle clean
        rm -rf "${directory:?}/"build
        rm -rf "${directory:?}/"bin
        rm -rf "${directory:?}/".gradle
    done
    ;;
esac
cd ~
